/**
 * Regenerates `src/herdr/types.generated.ts` from the Herdr API schema.
 *
 * The schema is committed at `schemas/herdr-api.schema.json` so CI — where no
 * Herdr daemon exists — can typecheck and test without the binary. Pass
 * `--refresh` to re-dump it from the live daemon first (`herdr api schema
 * --json`); that is the only step that needs Herdr installed.
 *
 * The schema's own `protocol` number is written into the generated banner.
 *
 * Carried over from a previous iteration that also kept a `PROTOCOL`
 * constant in `src/herdr/types.ts` plus a test asserting the two agree —
 * neither exists in this scaffold yet, so nothing currently guards against a
 * regeneration silently moving the protocol number. Add that constant and
 * test back before anything depends on `types.generated.ts`.
 */

import { compile } from "json-schema-to-typescript";
import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";

const SCHEMA_PATH = join("schemas", "herdr-api.schema.json");
const OUTPUT_PATH = join("src", "herdr", "types.generated.ts");

interface HerdrSchema {
  protocol: number;
  schema_version: number;
  schemas: Record<string, Record<string, unknown>>;
}

if (process.argv.includes("--refresh")) {
  const json = execFileSync("herdr", ["api", "schema", "--json"], { encoding: "utf8" });
  await mkdir("schemas", { recursive: true });
  await writeFile(SCHEMA_PATH, json);
  console.log(`refreshed ${SCHEMA_PATH} from the live daemon`);
}

const schema = JSON.parse(await readFile(SCHEMA_PATH, "utf8")) as HerdrSchema;
const parts: string[] = [
  `// GENERATED by scripts/gen-herdr-types.ts from ${SCHEMA_PATH} (protocol ${schema.protocol}). Do not edit.`,
  "/* eslint-disable */",
];

for (const [name, sub] of Object.entries(schema.schemas)) {
  // Each sub-schema keeps its own `$defs` under `#/schemas/<name>/$defs/`;
  // json-schema-to-typescript resolves `#/$defs/` only, so rewrite the pointers
  // before compiling the sub-schema standalone.
  const local = JSON.parse(
    JSON.stringify(sub).replaceAll(`#/schemas/${name}/$defs/`, "#/$defs/"),
  ) as Record<string, unknown>;
  const title =
    (sub.title as string | undefined) ??
    name
      .split("_")
      .map((segment) => segment[0]!.toUpperCase() + segment.slice(1))
      .join("");
  const typescript = await compile({ ...local, title }, title, {
    bannerComment: "",
    additionalProperties: false,
    strictIndexSignatures: true,
  });
  parts.push(`// ---- ${name} ----`, prefixGeneratedNames(typescript, title));
}

// Formatted with the repository's own prettier config so a regeneration never
// leaves `bun run format:check` failing.
const prettierConfig = await resolveConfig(OUTPUT_PATH);
const output = await format(parts.join("\n\n") + "\n", {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
});

await mkdir("src/herdr", { recursive: true });
await writeFile(OUTPUT_PATH, output);
console.log(`wrote ${OUTPUT_PATH} (protocol ${schema.protocol})`);

/**
 * Sub-schemas share helper type names (`AgentInfo` appears in more than one),
 * so every name but the sub-schema's own root is prefixed with its title.
 */
function prefixGeneratedNames(typescript: string, title: string): string {
  const names = [...typescript.matchAll(/export (?:interface|type) (\w+)/g)].map(
    (match) => match[1]!,
  );
  return names
    .filter((name) => name !== title)
    .reduce(
      (source, name) => source.replace(new RegExp(`\\b${name}\\b`, "g"), `${title}_${name}`),
      typescript,
    );
}
