#!/bin/sh
# Collect license files of every module linked into woof and woofd, across all
# release platforms, into third_party/licenses. `--check` verifies the committed
# copy is current. Fails when a linked module ships no license file.
set -eu
ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
mode=${1:-write}
case "$mode" in write|--check) ;; *) echo "Usage: $0 [--check]" >&2; exit 2 ;; esac
self=$(go list -m)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT HUP INT TERM
out="$work/licenses"
mkdir -p "$out"

for target in darwin/amd64 darwin/arm64 linux/amd64 linux/arm64; do
  GOOS=${target%/*} GOARCH=${target#*/} CGO_ENABLED=0 go list -deps \
    -f '{{with .Module}}{{.Path}} {{.Dir}}{{end}}' ./cmd/woof ./cmd/woofd
done | sort -u > "$work/modules"

while read -r path dir; do
  test "$path" != "$self" || continue
  test -n "$dir" && test -d "$dir" || { echo "licenses: module $path is not downloaded; run go mod download" >&2; exit 1; }
  found=false
  for f in "$dir"/*; do
    name=$(basename -- "$f")
    case "$name" in
      LICENSE*|LICENCE*|COPYING*|NOTICE*|PATENTS*|AUTHORS*)
        mkdir -p "$out/$path"
        cp "$f" "$out/$path/$name"
        chmod 644 "$out/$path/$name"
        case "$name" in AUTHORS*) ;; *) found=true ;; esac
        ;;
    esac
  done
  test "$found" = true || { echo "licenses: no license file found for $path" >&2; exit 1; }
done < "$work/modules"

# The Go standard library and runtime are linked into every binary.
mkdir -p "$out/go"
goroot=$(go env GOROOT)
if test -f "$goroot/LICENSE"; then
  cp "$goroot/LICENSE" "$out/go/LICENSE"
else
  # Some Go distributions omit GOROOT/LICENSE; golang.org/x modules carry the
  # identical Go Authors BSD license text.
  sys_dir=$(awk '$1 == "golang.org/x/sys" { print $2 }' "$work/modules")
  cp "$sys_dir/LICENSE" "$out/go/LICENSE"
fi
test ! -f "$goroot/PATENTS" || cp "$goroot/PATENTS" "$out/go/PATENTS"
chmod 644 "$out"/go/*

{
  echo "# Dependency licenses"
  echo
  echo "Generated by scripts/licenses.sh from the modules linked into woof and woofd"
  echo "for darwin and linux (amd64, arm64). Do not edit by hand."
  echo
  echo "- go (standard library and runtime)"
  awk -v self="$self" '$1 != self { print "- " $1 }' "$work/modules"
} > "$out/README.md"

dest=third_party/licenses
if test "$mode" = --check; then
  if ! diff -r "$out" "$dest" >/dev/null 2>&1; then
    echo "licenses: $dest is stale; run make licenses" >&2
    diff -r "$out" "$dest" | head -20 >&2 || true
    exit 1
  fi
  echo "licenses: $dest is current"
  exit 0
fi
rm -rf "$dest"
mkdir -p third_party
cp -R "$out" "$dest"
echo "licenses: wrote $dest"
