const {Logo,Button,IconButton,Badge,Chip,Table,Tabs,Card,Icon}=window.WoofDesignSystem_3b6aec;

function Nav({theme,onTheme}){
  return <nav style={{height:52,borderBottom:"1px solid var(--border-subtle)",background:"var(--bg-app)",position:"sticky",top:0,zIndex:10}}><div className="wrap" style={{display:"flex",alignItems:"center",gap:20,height:"100%"}}><Logo size={28} withName base="../../assets/brand" theme={theme}/><Badge tone="accent">v0.1.0 pre-release</Badge><span style={{flex:1}}/>{["Install","Commands","Exit codes","Docs"].map(l=><a key={l} href={"#"+l.toLowerCase().replace(" ","-")} style={{font:"var(--type-small)",color:"var(--text-secondary)"}}>{l}</a>)}<Button size="sm" icon="github">zielus/herdr-woof</Button><IconButton icon={theme==="light"?"moon":"sun"} label="Toggle theme" onClick={onTheme}/></div></nav>;
}

function Hero(){
  return <section className="wrap" style={{padding:"72px 24px 56px",display:"grid",gridTemplateColumns:"minmax(0,1.1fr) minmax(0,1fr)",gap:48,alignItems:"center"}}>
    <div><h1 style={{font:"var(--type-display)",letterSpacing:"var(--tracking-tight)",margin:"0 0 20px",color:"var(--text-primary)",textWrap:"pretty"}}>Bounded, journaled workflows for coding agents on Herdr.</h1><p style={{font:"var(--type-body)",fontSize:16}}>Woof runs plan → build → verify → review → repair across real agent sessions in Herdr panes and hands a structured, hash-verified result back to the caller. Open source. Developer-facing. Not finished.</p><div style={{display:"flex",gap:8,marginTop:24}}><Button variant="primary" size="lg" icon="terminal">Install the plugin</Button><Button size="lg" iconRight="arrowRight">Read the docs</Button></div><div style={{display:"flex",gap:16,marginTop:20,font:"var(--type-mono-sm)",color:"var(--text-muted)"}}><span>macOS · Linux</span><span>Node ≥ 22.18</span><span>Herdr ≥ 0.9.0</span></div></div>
    <div className="pre" style={{fontSize:12}}><div><span className="p">$</span> woof run start --workflow plan-build-review --input input.json</div><div className="c">{'{"outcome":"started","runId":"br-4f2a9c","host":{"mode":"herdr-pane"}}'}</div><div style={{height:8}}/><div><span className="p">$</span> woof status /abs/run --wait</div><div className="c">running plan v1 a1 r1 … running build v1 a2 r1 … running review v1 a1 r1</div><div><span style={{color:"var(--state-fail)"}}>gate.recorded</span> <span className="c">review reject r1</span></div><div className="c">running repair v1 a1 r2 … running review v2 a1 r2</div><div><span style={{color:"var(--state-pass)"}}>gate.recorded</span> <span className="c">review pass r2</span></div><div><span style={{color:"var(--state-pass)"}}>{'{"outcome":"completed","limit":null,"counters":{"rounds":2}}'}</span></div><div className="c"># exit 0</div></div>
  </section>;
}

function What(){
  const items=[["Stages, not chat","Every unit of work is a stage visit with numbered attempts. A reviewer's verdict is a gate; a failing gate routes to repair, never back to plan."],["Journal is the truth","An append-only journal.jsonl in the run directory. Snapshots, events and status are derived from it. No second reducer."],["Hash-verified handoff","Workers submit a small envelope naming an artifact and its sha256. Woof validates and records; --verify-artifacts re-hashes later."],["Finite limits","maxRounds, maxAttemptsPerVisit, maxVisitsPerStage, timeouts. Reaching one ends the run as exhausted with the limit named."],["Blocking is visible","An untrusted repo or a prompt waiting on input records run.blocked with a requiredAction. Woof never answers the prompt for you."],["Read-only inspection","status, runs, events and config show take no journal lock and never contact Herdr."]];
  return <section className="wrap" style={{padding:"32px 24px 56px"}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:16}}>{items.map(([t,d])=><Card key={t}><div style={{font:"var(--type-heading)",marginBottom:6,color:"var(--text-primary)"}}>{t}</div><p style={{font:"var(--type-small)",fontSize:13}}>{d}</p></Card>)}</div></section>;
}

function Install(){
  const [tab,setTab]=React.useState("herdr");
  const code={herdr:[["$","herdr plugin link ."],["$","herdr plugin action list --plugin herdr-woof"],["#","doctor · status · start · cancel"]],claude:[["$","claude --plugin-dir plugin/claude"],["#","/woof:run <task description>"],["#","/woof:run --workflow plan-build-review <task>"]],cli:[["$","bun install --frozen-lockfile && bun run build"],["$","bin/woof doctor --json"],["#",'{"herdr":{"env":true},"claude":{"found":true},"trust":{"status":"trusted"}}']]};
  return <section id="install" className="wrap" style={{padding:"32px 24px 56px",display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(0,1.4fr)",gap:48}}><div><h2>Install</h2><p>Three surfaces, one product. The Herdr plugin adds four actions; the Claude Code plugin adds <code>/woof:run</code>; the CLI is for inspection, debugging and automation.</p><p style={{marginTop:12,font:"var(--type-small)"}}>Before the first run, open <code>claude</code> in the target repository once and accept its folder-trust question. Woof reports trust status; it never bypasses the dialog.</p></div><div><Tabs value={tab} onChange={setTab} tabs={[{id:"herdr",label:"Herdr plugin"},{id:"claude",label:"Claude Code plugin"},{id:"cli",label:"CLI"}]} style={{marginBottom:12}}/><div className="pre">{code[tab].map(([k,l],i)=><div key={i} className={k==="#"?"c":""}>{k==="$"&&<span className="p">$ </span>}{k==="#"&&"# "}{l}</div>)}</div></div></section>;
}

function Commands(){
  const rows=[["woof run start","Host a workflow run in a Herdr pane; returns once the run is claimed and opened.","unstable"],["woof status <run-dir> [--wait]","Status, owner liveness, active attempts, last gate; --wait polls to a terminal exit code.","read-only"],["woof runs","Runs under ~/.woof/runs or a project; owner reported as unhosted, alive, lost or exited.","read-only"],["woof events <run-dir> [--follow]","One event per journal record, resumable by cursor.","read-only"],["woof run show <run-dir>","Snapshot: agents, per-stage attempts, counters, ambiguous deliveries.","read-only"],["woof run cancel <run-dir>","Records run.terminated{outcome:\"cancelled\"}; the scheduler stops on its next tick.","unstable"],["woof config show","Effective configuration and where each value came from.","read-only"],["woof doctor [--json]","Herdr, Claude Code, folder trust and configuration checks. Always exits 0.","diagnostic"]].map(([c,d,t])=>({c,d,t}));
  return <section id="commands" className="wrap" style={{padding:"32px 24px 56px"}}><h2>Commands</h2><p style={{marginBottom:16}}>Progress goes to stderr; stdout prints exactly one JSON line.</p><Card padding={0}><Table rows={rows} rowKey="c" columns={[{key:"c",label:"Command",mono:true,width:300},{key:"d",label:"What it does",render:r=><span style={{whiteSpace:"normal"}}>{r.d}</span>},{key:"t",label:"Contract",align:"right",render:r=><Badge>{r.t}</Badge>}]}/></Card></section>;
}

function ExitCodes(){
  const codes=[[0,"completed","pass"],[1,"usage error","idle"],[2,"rejected before launch","fail"],[3,"infrastructure failure","fail"],[4,"failed","fail"],[5,"exhausted — a limit ended the run","blocked"],[6,"cancelled","lost"],[7,"still running at --timeout-ms","working"],[8,"owner gone without a recorded outcome (lost / exited)","lost"],[9,"blocked and needs the operator","blocked"]];
  return <section id="exit-codes" className="wrap" style={{padding:"32px 24px 72px"}}><h2>Exit codes</h2><p style={{marginBottom:16}}>A recorded outcome always wins. The last line printed is the status at return time.</p><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:8}}>{codes.map(([n,d,t])=><div key={n} style={{border:"1px solid var(--border-default)",borderRadius:"var(--radius-md)",background:"var(--bg-surface)",padding:"10px 12px",display:"grid",gap:6}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><span style={{font:"var(--type-mono)",fontSize:20,fontWeight:500,color:"var(--text-primary)"}}>{n}</span><Chip size="sm" tone={t} state={t} dot={true} pulse={false}>{t}</Chip></div><div style={{font:"var(--type-small)",color:"var(--text-secondary)"}}>{d}</div></div>)}</div></section>;
}

function Footer(){
  return <footer style={{borderTop:"1px solid var(--border-subtle)"}}><div className="wrap" style={{display:"flex",alignItems:"center",gap:16,height:64,font:"var(--type-mono-sm)",color:"var(--text-muted)"}}><Logo size={20} base="../../assets/brand"/><span>Woof v0.1.0 · Herdr ≥ 0.9.0</span><span style={{flex:1}}/><span>It does not delegate agents outside a workflow, resume a crashed run, or run parallel work within a run.</span></div></footer>;
}

function Site(){
  const [theme,setTheme]=React.useState(localStorage.getItem("woof-theme")||"dark");
  React.useEffect(()=>{document.documentElement.setAttribute("data-theme",theme);localStorage.setItem("woof-theme",theme)},[theme]);
  return <div><Nav theme={theme} onTheme={()=>setTheme(t=>t==="dark"?"light":"dark")}/><Hero/><What/><Install/><Commands/><ExitCodes/><Footer/></div>;
}
ReactDOM.createRoot(document.getElementById("root")).render(<Site/>);
